import { Card } from '@7wonders/shared';

// Each entry in minPlayers means one copy of the card is added per listed value.
// E.g. minPlayers: [3, 4] → two copies total: one for 3+ players, one for 4+ players.
// The deck builder will include all copies where playerCount >= minPlayers[i].

export const AGE1_CARDS: Card[] = [
  // ── MATERIA PRIMA (brown) ─────────────────────────────────────────────────
  {
    id: 'lumber_yard_3',
    name: 'Bosque de Lenga',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'wood' }],
  },
  {
    id: 'lumber_yard_4',
    name: 'Bosque de Lenga',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'wood' }],
  },
  {
    id: 'stone_pit_3',
    name: 'Cantera',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'stone_pit_5',
    name: 'Cantera',
    color: 'brown',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'clay_pool_3',
    name: 'Greda del Río',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'clay' }],
  },
  {
    id: 'clay_pool_5',
    name: 'Greda del Río',
    color: 'brown',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'clay' }],
  },
  {
    id: 'ore_vein_3',
    name: 'Veta de Hueso',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'ore_vein_4',
    name: 'Veta de Hueso',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'tree_farm',
    name: 'Claro del Monte',
    color: 'brown',
    age: 1,
    minPlayers: [6],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['wood', 'clay'] }],
  },
  {
    id: 'excavation',
    name: 'Excavación',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'clay'] }],
  },
  {
    id: 'clay_pit',
    name: 'Barranca de Greda',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['clay', 'ore'] }],
  },
  {
    id: 'timber_yard',
    name: 'Corral de Troncos',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'wood'] }],
  },
  {
    id: 'forest_cave',
    name: 'Cueva del Bosque',
    color: 'brown',
    age: 1,
    minPlayers: [5],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['wood', 'ore'] }],
  },
  {
    id: 'mine',
    name: 'Mina',
    color: 'brown',
    age: 1,
    minPlayers: [6],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'ore'] }],
  },

  // ── MANUFACTURA (gray) ─────────────────────────────────────────────────────
  {
    id: 'loom_3',
    name: 'Telar',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'loom_6',
    name: 'Telar',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'glassworks_3',
    name: 'Obsidiana',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'glassworks_6',
    name: 'Obsidiana',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'press_3',
    name: 'Taller de Corteza',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },
  {
    id: 'press_6',
    name: 'Taller de Corteza',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },

  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  {
    id: 'pawnshop_4',
    name: 'Casa del Trueque',
    color: 'blue',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'pawnshop_7',
    name: 'Casa del Trueque',
    color: 'blue',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: [],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'baths_3',
    name: 'Vertiente Termal',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: { stone: 1 },
    chainTo: ['Canal de Riego'],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'baths_7',
    name: 'Vertiente Termal',
    color: 'blue',
    age: 1,
    minPlayers: [7],
    cost: { stone: 1 },
    chainTo: ['Canal de Riego'],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'altar_3',
    name: 'Rehue',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Kamaruko'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'altar_5',
    name: 'Rehue',
    color: 'blue',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: ['Kamaruko'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'theater_3',
    name: 'Ruka de Reunión',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Kemu-Kemu'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'theater_6',
    name: 'Ruka de Reunión',
    color: 'blue',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: ['Kemu-Kemu'],
    effects: [{ type: 'victory_points', points: 2 }],
  },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  {
    id: 'apothecary_3',
    name: 'Lawentuchefe',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { loom: 1 },
    chainFrom: undefined,
    chainTo: ['Tropa de Caballos', 'Sanadora'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'apothecary_5',
    name: 'Lawentuchefe',
    color: 'green',
    age: 1,
    minPlayers: [5],
    cost: { loom: 1 },
    chainTo: ['Tropa de Caballos', 'Sanadora'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'workshop_3',
    name: 'Taller de la Machi',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { glass: 1 },
    chainTo: ['Arquero', 'Logia de la Luna'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'workshop_7',
    name: 'Taller de la Machi',
    color: 'green',
    age: 1,
    minPlayers: [7],
    cost: { glass: 1 },
    chainTo: ['Arquero', 'Logia de la Luna'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'scriptorium_3',
    name: 'Quipucamayoc',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { papyrus: 1 },
    chainTo: ['Consejo de Lonkos', 'Archivo de Quipus'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },
  {
    id: 'scriptorium_4',
    name: 'Quipucamayoc',
    color: 'green',
    age: 1,
    minPlayers: [4],
    cost: { papyrus: 1 },
    chainTo: ['Consejo de Lonkos', 'Archivo de Quipus'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  {
    id: 'east_trading_post_3',
    name: 'Posta del Este',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Tambo'],
    effects: [{ type: 'trade_discount_right', resources: ['brown'] }],
  },
  {
    id: 'east_trading_post_7',
    name: 'Posta del Este',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: ['Tambo'],
    effects: [{ type: 'trade_discount_right', resources: ['brown'] }],
  },
  {
    id: 'west_trading_post_3',
    name: 'Posta del Oeste',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Tambo'],
    effects: [{ type: 'trade_discount_left', resources: ['brown'] }],
  },
  {
    id: 'west_trading_post_6',
    name: 'Posta del Oeste',
    color: 'yellow',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: ['Tambo'],
    effects: [{ type: 'trade_discount_left', resources: ['brown'] }],
  },
  {
    id: 'marketplace_3',
    name: 'Mercado de la Pampa',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Caravana del Lof'],
    effects: [{ type: 'trade_discount_both', resources: ['gray'] }],
  },
  {
    id: 'marketplace_7',
    name: 'Mercado de la Pampa',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: ['Caravana del Lof'],
    effects: [{ type: 'trade_discount_both', resources: ['gray'] }],
  },
  {
    id: 'tavern_4',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern_5',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern_7',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  {
    id: 'stockade_3',
    name: 'Empalizada',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'stockade_7',
    name: 'Empalizada',
    color: 'red',
    age: 1,
    minPlayers: [7],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'barracks_3',
    name: 'Toldería de Guerreros',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { ore: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'barracks_5',
    name: 'Toldería de Guerreros',
    color: 'red',
    age: 1,
    minPlayers: [5],
    cost: { ore: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'guard_tower_3',
    name: 'Atalaya',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { clay: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'guard_tower_4',
    name: 'Atalaya',
    color: 'red',
    age: 1,
    minPlayers: [4],
    cost: { clay: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// ERA II
// ══════════════════════════════════════════════════════════════════════════════
export const AGE2_CARDS: Card[] = [
  // ── MATERIA PRIMA (brown) ─────────────────────────────────────────────────
  { id: 'a2_sawmill_3', name: 'Aserradero de Lenga', color: 'brown', age: 2, minPlayers: [3], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'wood' }, { type: 'produce_resource', resource: 'wood' }] },
  { id: 'a2_sawmill_4', name: 'Aserradero de Lenga', color: 'brown', age: 2, minPlayers: [4], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'wood' }, { type: 'produce_resource', resource: 'wood' }] },
  { id: 'a2_quarry_3', name: 'Cantera Mayor', color: 'brown', age: 2, minPlayers: [3], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'stone' }, { type: 'produce_resource', resource: 'stone' }] },
  { id: 'a2_quarry_4', name: 'Cantera Mayor', color: 'brown', age: 2, minPlayers: [4], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'stone' }, { type: 'produce_resource', resource: 'stone' }] },
  { id: 'a2_brickyard_3', name: 'Adobera', color: 'brown', age: 2, minPlayers: [3], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'clay' }, { type: 'produce_resource', resource: 'clay' }] },
  { id: 'a2_brickyard_4', name: 'Adobera', color: 'brown', age: 2, minPlayers: [4], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'clay' }, { type: 'produce_resource', resource: 'clay' }] },
  { id: 'a2_foundry_3', name: 'Osario', color: 'brown', age: 2, minPlayers: [3], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }] },
  { id: 'a2_foundry_4', name: 'Osario', color: 'brown', age: 2, minPlayers: [4], cost: { coins: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }] },

  // ── MANUFACTURA (gray) ────────────────────────────────────────────────────
  { id: 'a2_loom_3', name: 'Telar', color: 'gray', age: 2, minPlayers: [3], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'loom' }] },
  { id: 'a2_loom_5', name: 'Telar', color: 'gray', age: 2, minPlayers: [5], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'loom' }] },
  { id: 'a2_glassworks_3', name: 'Obsidiana', color: 'gray', age: 2, minPlayers: [3], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'glass' }] },
  { id: 'a2_glassworks_5', name: 'Obsidiana', color: 'gray', age: 2, minPlayers: [5], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'glass' }] },
  { id: 'a2_press_3', name: 'Taller de Corteza', color: 'gray', age: 2, minPlayers: [3], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'papyrus' }] },
  { id: 'a2_press_5', name: 'Taller de Corteza', color: 'gray', age: 2, minPlayers: [5], cost: {}, chainTo: [], effects: [{ type: 'produce_resource', resource: 'papyrus' }] },

  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  { id: 'a2_aqueduct_3', name: 'Canal de Riego', color: 'blue', age: 2, minPlayers: [3], cost: { stone: 3 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a2_aqueduct_7', name: 'Canal de Riego', color: 'blue', age: 2, minPlayers: [7], cost: { stone: 3 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a2_temple_3', name: 'Kamaruko', color: 'blue', age: 2, minPlayers: [3], cost: { wood: 1, clay: 1, glass: 1 }, chainTo: ['Nguillatún'], effects: [{ type: 'victory_points', points: 3 }] },
  { id: 'a2_temple_6', name: 'Kamaruko', color: 'blue', age: 2, minPlayers: [6], cost: { wood: 1, clay: 1, glass: 1 }, chainTo: ['Nguillatún'], effects: [{ type: 'victory_points', points: 3 }] },
  { id: 'a2_statue_3', name: 'Kemu-Kemu', color: 'blue', age: 2, minPlayers: [3], cost: { ore: 2, wood: 1 }, chainTo: ['Jardín del Sur'], effects: [{ type: 'victory_points', points: 4 }] },
  { id: 'a2_statue_7', name: 'Kemu-Kemu', color: 'blue', age: 2, minPlayers: [7], cost: { ore: 2, wood: 1 }, chainTo: ['Jardín del Sur'], effects: [{ type: 'victory_points', points: 4 }] },
  { id: 'a2_courthouse_3', name: 'Consejo de Lonkos', color: 'blue', age: 2, minPlayers: [3], cost: { clay: 2, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 4 }] },
  { id: 'a2_courthouse_5', name: 'Consejo de Lonkos', color: 'blue', age: 2, minPlayers: [5], cost: { clay: 2, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 4 }] },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  { id: 'a2_dispensary_3', name: 'Sanadora', color: 'green', age: 2, minPlayers: [3], cost: { ore: 2, glass: 1 }, chainTo: ['Ring de Lucha', 'Círculo de Ancianos'], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a2_dispensary_4', name: 'Sanadora', color: 'green', age: 2, minPlayers: [4], cost: { ore: 2, glass: 1 }, chainTo: ['Ring de Lucha', 'Círculo de Ancianos'], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a2_laboratory_3', name: 'Logia de la Luna', color: 'green', age: 2, minPlayers: [3], cost: { clay: 2, papyrus: 1 }, chainTo: ['Taller de Lanzas', 'Observatorio del Cielo'], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a2_laboratory_5', name: 'Logia de la Luna', color: 'green', age: 2, minPlayers: [5], cost: { clay: 2, papyrus: 1 }, chainTo: ['Taller de Lanzas', 'Observatorio del Cielo'], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a2_library_3', name: 'Archivo de Quipus', color: 'green', age: 2, minPlayers: [3], cost: { stone: 2, loom: 1 }, chainTo: ['Asamblea Grande', 'Universidad del Sur'], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a2_library_6', name: 'Archivo de Quipus', color: 'green', age: 2, minPlayers: [6], cost: { stone: 2, loom: 1 }, chainTo: ['Asamblea Grande', 'Universidad del Sur'], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a2_school_3', name: 'Escuela del Sur', color: 'green', age: 2, minPlayers: [3], cost: { wood: 1, papyrus: 1 }, chainTo: ['Academia del Saber', 'Estudio del Cielo'], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a2_school_7', name: 'Escuela del Sur', color: 'green', age: 2, minPlayers: [7], cost: { wood: 1, papyrus: 1 }, chainTo: ['Academia del Saber', 'Estudio del Cielo'], effects: [{ type: 'science', symbol: 'tablet' }] },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  { id: 'a2_forum_3', name: 'Tambo', color: 'yellow', age: 2, minPlayers: [3], cost: { clay: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['glass', 'loom', 'papyrus'] }] },
  { id: 'a2_forum_6', name: 'Tambo', color: 'yellow', age: 2, minPlayers: [6], cost: { clay: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['glass', 'loom', 'papyrus'] }] },
  { id: 'a2_forum_7', name: 'Tambo', color: 'yellow', age: 2, minPlayers: [7], cost: { clay: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['glass', 'loom', 'papyrus'] }] },
  { id: 'a2_caravansery_3', name: 'Caravana del Lof', color: 'yellow', age: 2, minPlayers: [3], cost: { wood: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'stone', 'clay', 'ore'] }] },
  { id: 'a2_caravansery_5', name: 'Caravana del Lof', color: 'yellow', age: 2, minPlayers: [5], cost: { wood: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'stone', 'clay', 'ore'] }] },
  { id: 'a2_caravansery_6', name: 'Caravana del Lof', color: 'yellow', age: 2, minPlayers: [6], cost: { wood: 2 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'stone', 'clay', 'ore'] }] },
  { id: 'a2_vineyard_3', name: 'Viña Patagónica', color: 'yellow', age: 2, minPlayers: [3], cost: {}, chainTo: [], effects: [{ type: 'coins_from_brown', per_brown: 1, include_neighbors: true }] },
  { id: 'a2_vineyard_6', name: 'Viña Patagónica', color: 'yellow', age: 2, minPlayers: [6], cost: {}, chainTo: [], effects: [{ type: 'coins_from_brown', per_brown: 1, include_neighbors: true }] },
  { id: 'a2_bazar_4', name: 'Feria de Trueque', color: 'yellow', age: 2, minPlayers: [4], cost: {}, chainTo: [], effects: [{ type: 'coins_from_gray', per_gray: 2, include_neighbors: true }] },
  { id: 'a2_bazar_7', name: 'Feria de Trueque', color: 'yellow', age: 2, minPlayers: [7], cost: {}, chainTo: [], effects: [{ type: 'coins_from_gray', per_gray: 2, include_neighbors: true }] },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  { id: 'a2_walls_3', name: 'Muralla de Piedra', color: 'red', age: 2, minPlayers: [3], cost: { stone: 3 }, chainTo: ['Fortificación del Malón'], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_walls_7', name: 'Muralla de Piedra', color: 'red', age: 2, minPlayers: [7], cost: { stone: 3 }, chainTo: ['Fortificación del Malón'], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_training_ground_4', name: 'Campo de Adiestramiento', color: 'red', age: 2, minPlayers: [4], cost: { ore: 2, wood: 1 }, chainTo: ['Ruedo de Guerra'], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_training_ground_6', name: 'Campo de Adiestramiento', color: 'red', age: 2, minPlayers: [6], cost: { ore: 2, wood: 1 }, chainTo: ['Ruedo de Guerra'], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_training_ground_7', name: 'Campo de Adiestramiento', color: 'red', age: 2, minPlayers: [7], cost: { ore: 2, wood: 1 }, chainTo: ['Ruedo de Guerra'], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_stables_3', name: 'Tropa de Caballos', color: 'red', age: 2, minPlayers: [3], cost: { clay: 1, wood: 1, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_stables_5', name: 'Tropa de Caballos', color: 'red', age: 2, minPlayers: [5], cost: { clay: 1, wood: 1, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_archery_range_3', name: 'Arquero', color: 'red', age: 2, minPlayers: [3], cost: { wood: 2, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 2 }] },
  { id: 'a2_archery_range_6', name: 'Arquero', color: 'red', age: 2, minPlayers: [6], cost: { wood: 2, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 2 }] },
];

// ══════════════════════════════════════════════════════════════════════════════
// ERA III
// ══════════════════════════════════════════════════════════════════════════════
export const AGE3_CARDS: Card[] = [
  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  { id: 'a3_pantheon_3', name: 'Nguillatún', color: 'blue', age: 3, minPlayers: [3], cost: { clay: 1, wood: 1, papyrus: 1, loom: 1, glass: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'a3_pantheon_6', name: 'Nguillatún', color: 'blue', age: 3, minPlayers: [6], cost: { clay: 1, wood: 1, papyrus: 1, loom: 1, glass: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'a3_gardens_3', name: 'Jardín del Sur', color: 'blue', age: 3, minPlayers: [3], cost: { clay: 2, wood: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a3_gardens_4', name: 'Jardín del Sur', color: 'blue', age: 3, minPlayers: [4], cost: { clay: 2, wood: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a3_town_hall_3', name: 'Asamblea del Pueblo', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 2, wood: 1, glass: 1, ore: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_town_hall_5', name: 'Asamblea del Pueblo', color: 'blue', age: 3, minPlayers: [5], cost: { stone: 2, wood: 1, glass: 1, ore: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_palace_3', name: 'Ruka del Lonko Mayor', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 1, clay: 1, ore: 1, wood: 1, glass: 1, loom: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 8 }] },
  { id: 'a3_palace_7', name: 'Ruka del Lonko Mayor', color: 'blue', age: 3, minPlayers: [7], cost: { stone: 1, clay: 1, ore: 1, wood: 1, glass: 1, loom: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 8 }] },
  { id: 'a3_senate_3', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [3], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_senate_5', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [5], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_senate_7', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [7], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  { id: 'a3_lodge_3', name: 'Círculo de Ancianos', color: 'green', age: 3, minPlayers: [3], cost: { clay: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_lodge_6', name: 'Círculo de Ancianos', color: 'green', age: 3, minPlayers: [6], cost: { clay: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_observatory_3', name: 'Observatorio del Cielo', color: 'green', age: 3, minPlayers: [3], cost: { ore: 2, wood: 1, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_observatory_7', name: 'Observatorio del Cielo', color: 'green', age: 3, minPlayers: [7], cost: { ore: 2, wood: 1, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_university_3', name: 'Universidad del Sur', color: 'green', age: 3, minPlayers: [3], cost: { wood: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a3_university_4', name: 'Universidad del Sur', color: 'green', age: 3, minPlayers: [4], cost: { wood: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a3_academy_3', name: 'Academia del Saber', color: 'green', age: 3, minPlayers: [3], cost: { stone: 3, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_academy_6', name: 'Academia del Saber', color: 'green', age: 3, minPlayers: [6], cost: { stone: 3, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_study_3', name: 'Estudio del Cielo', color: 'green', age: 3, minPlayers: [3], cost: { wood: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_study_5', name: 'Estudio del Cielo', color: 'green', age: 3, minPlayers: [5], cost: { wood: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  { id: 'a3_haven_3', name: 'Caleta', color: 'yellow', age: 3, minPlayers: [3], cost: { ore: 1, loom: 1, wood: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_brown', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_haven_4', name: 'Caleta', color: 'yellow', age: 3, minPlayers: [4], cost: { ore: 1, loom: 1, wood: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_brown', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_lighthouse_3', name: 'Fogón Guía', color: 'yellow', age: 3, minPlayers: [3], cost: { stone: 1, glass: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_yellow', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_lighthouse_6', name: 'Fogón Guía', color: 'yellow', age: 3, minPlayers: [6], cost: { stone: 1, glass: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_yellow', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_chamber_4', name: 'Cámara del Trueque', color: 'yellow', age: 3, minPlayers: [4], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_gray', per_card: 2, vp_per_card: 2 }] },
  { id: 'a3_chamber_6', name: 'Cámara del Trueque', color: 'yellow', age: 3, minPlayers: [6], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_gray', per_card: 2, vp_per_card: 2 }] },
  { id: 'a3_arena_3', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [3], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },
  { id: 'a3_arena_5', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [5], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },
  { id: 'a3_arena_7', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [7], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  { id: 'a3_fortifications_3', name: 'Fortificación del Malón', color: 'red', age: 3, minPlayers: [3], cost: { ore: 3, stone: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_fortifications_7', name: 'Fortificación del Malón', color: 'red', age: 3, minPlayers: [7], cost: { ore: 3, stone: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_4', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [4], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_5', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [5], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_6', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [6], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_3', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [3], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_4', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [4], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_7', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [7], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_siege_workshop_3', name: 'Taller de Lanzas', color: 'red', age: 3, minPlayers: [3], cost: { clay: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_siege_workshop_5', name: 'Taller de Lanzas', color: 'red', age: 3, minPlayers: [5], cost: { clay: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },

  // ── GREMIOS (purple) — Era III; deckBuilder selects playerCount+2 randomly ──
  { id: 'g_workers', name: 'Lof de Trabajadores', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, clay: 1, wood: 1, stone: 1 }, chainTo: [], effects: [{ type: 'vp_from_brown_neighbors', per_card: 1 }] },
  { id: 'g_craftsmens', name: 'Lof de Artesanos', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, stone: 2 }, chainTo: [], effects: [{ type: 'vp_from_gray_neighbors', per_card: 2 }] },
  { id: 'g_traders', name: 'Lof de Comerciantes', color: 'purple', age: 3, minPlayers: [3], cost: { glass: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_yellow_neighbors', per_card: 1 }] },
  { id: 'g_philosophers', name: 'Lof de Machis', color: 'purple', age: 3, minPlayers: [3], cost: { clay: 3, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_green_neighbors', per_card: 1 }] },
  { id: 'g_spies', name: 'Lof de Rastreadores', color: 'purple', age: 3, minPlayers: [3], cost: { clay: 3, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_red_neighbors', per_card: 1 }] },
  { id: 'g_magistrates', name: 'Lof de Lonkos', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 3, stone: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_blue_neighbors', per_card: 1 }] },
  { id: 'g_shipowners', name: 'Lof de Canoeros', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 3, glass: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'vp_from_own_brown_gray_purple' }] },
  { id: 'g_strategists', name: 'Lof de Toquis', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, stone: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_defeat_tokens_neighbors' }] },
  { id: 'g_scientists', name: 'Lof de Kimche', color: 'purple', age: 3, minPlayers: [4], cost: { wood: 2, ore: 2, glass: 1 }, chainTo: [], effects: [{ type: 'extra_science_symbol' }] },
  { id: 'g_builders', name: 'Lof de Constructores', color: 'purple', age: 3, minPlayers: [3], cost: { stone: 2, clay: 2, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_wonder_stages', include_self: true }] },
];
