import { Card } from '@7wonders/shared';

// Each entry in minPlayers means one copy of the card is added per listed value.
// E.g. minPlayers: [3, 4] → two copies total: one for 3+ players, one for 4+ players.
// The deck builder will include all copies where playerCount >= minPlayers[i].

export const AGE1_CARDS: Card[] = [
  // ── MATERIA PRIMA (brown) ─────────────────────────────────────────────────
  {
    id: 'lumber_yard_3',
    name: 'Bosque de Lenga',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'wood' }],
  },
  {
    id: 'lumber_yard_4',
    name: 'Bosque de Lenga',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'wood' }],
  },
  {
    id: 'stone_pit_3',
    name: 'Cantera',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'stone_pit_5',
    name: 'Cantera',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'clay_pool_3',
    name: 'Greda del Río',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'clay' }],
  },
  {
    id: 'clay_pool_5',
    name: 'Greda del Río',
    color: 'brown',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'clay' }],
  },
  {
    id: 'ore_vein_3',
    name: 'Veta de Hueso',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'ore_vein_4',
    name: 'Veta de Hueso',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'tree_farm',
    name: 'Claro del Monte',
    color: 'brown',
    age: 1,
    minPlayers: [6],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['wood', 'clay'] }],
  },
  {
    id: 'excavation',
    name: 'Excavación',
    color: 'brown',
    age: 1,
    minPlayers: [4],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'clay'] }],
  },
  {
    id: 'clay_pit',
    name: 'Barranca de Greda',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['clay', 'ore'] }],
  },
  {
    id: 'timber_yard',
    name: 'Corral de Troncos',
    color: 'brown',
    age: 1,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'wood'] }],
  },
  {
    id: 'forest_cave',
    name: 'Cueva del Bosque',
    color: 'brown',
    age: 1,
    minPlayers: [5],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['wood', 'ore'] }],
  },
  {
    id: 'mine',
    name: 'Mina',
    color: 'brown',
    age: 1,
    minPlayers: [6],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'ore'] }],
  },

  // ── MANUFACTURA (gray) ─────────────────────────────────────────────────────
  {
    id: 'loom_3',
    name: 'Witral',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'loom_6',
    name: 'Witral',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'glassworks_3',
    name: 'Obsidiana',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'glassworks_6',
    name: 'Obsidiana',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'press_3',
    name: 'Taller de Corteza',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },
  {
    id: 'press_6',
    name: 'Taller de Corteza',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },

  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  {
    id: 'pawnshop_4',
    name: 'Casa del Trueque',
    color: 'blue',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'pawnshop_7',
    name: 'Casa del Trueque',
    color: 'blue',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: [],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'baths_3',
    name: 'Vertiente Termal',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: { stone: 1 },
    chainTo: ['Maloca Ceremonial'],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'baths_7',
    name: 'Vertiente Termal',
    color: 'blue',
    age: 1,
    minPlayers: [7],
    cost: { stone: 1 },
    chainTo: ['Maloca Ceremonial'],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'altar_3',
    name: 'Rehue',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Parlamento de Lonkos'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'altar_5',
    name: 'Rehue',
    color: 'blue',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: ['Parlamento de Lonkos'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'theater_3',
    name: 'Ruka de Reunión',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Escuela de la Naturaleza'],
    effects: [{ type: 'victory_points', points: 2 }],
  },
  {
    id: 'theater_6',
    name: 'Ruka de Reunión',
    color: 'blue',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: ['Escuela de la Naturaleza'],
    effects: [{ type: 'victory_points', points: 2 }],
  },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  {
    id: 'apothecary_3',
    name: 'Lawentuchefe',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { loom: 1 },
    chainFrom: undefined,
    chainTo: ['Observatorio de la Cruz del Sur', 'Práctica de Arquería'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'apothecary_5',
    name: 'Lawentuchefe',
    color: 'green',
    age: 1,
    minPlayers: [5],
    cost: { loom: 1 },
    chainTo: ['Observatorio de la Cruz del Sur', 'Práctica de Arquería'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'workshop_3',
    name: 'Taller de la Machi',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { glass: 1 },
    chainTo: ['Taller de Boleadoras y Lazos', 'Huerto de Hierbas Curativas'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'workshop_7',
    name: 'Taller de la Machi',
    color: 'green',
    age: 1,
    minPlayers: [7],
    cost: { glass: 1 },
    chainTo: ['Taller de Boleadoras y Lazos', 'Huerto de Hierbas Curativas'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'scriptorium_3',
    name: 'Quipucamayoc',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { papyrus: 1 },
    chainTo: ['Círculo de Historias Orales'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },
  {
    id: 'scriptorium_4',
    name: 'Quipucamayoc',
    color: 'green',
    age: 1,
    minPlayers: [4],
    cost: { papyrus: 1 },
    chainTo: ['Círculo de Historias Orales'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  {
    id: 'east_trading_post_3',
    name: 'Posta del Este',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Mercado de las Carretas'],
    effects: [{ type: 'trade_discount_right', resources: ['brown'] }],
  },
  {
    id: 'east_trading_post_7',
    name: 'Posta del Este',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: ['Mercado de las Carretas'],
    effects: [{ type: 'trade_discount_right', resources: ['brown'] }],
  },
  {
    id: 'west_trading_post_3',
    name: 'Posta del Oeste',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Mercado de las Carretas'],
    effects: [{ type: 'trade_discount_left', resources: ['brown'] }],
  },
  {
    id: 'west_trading_post_6',
    name: 'Posta del Oeste',
    color: 'yellow',
    age: 1,
    minPlayers: [6],
    cost: {},
    chainTo: ['Mercado de las Carretas'],
    effects: [{ type: 'trade_discount_left', resources: ['brown'] }],
  },
  {
    id: 'marketplace_3',
    name: 'Mercado de la Pampa',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: ['Depósito de Vituallas'],
    effects: [{ type: 'trade_discount_both', resources: ['gray'] }],
  },
  {
    id: 'marketplace_7',
    name: 'Mercado de la Pampa',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: ['Depósito de Vituallas'],
    effects: [{ type: 'trade_discount_both', resources: ['gray'] }],
  },
  {
    id: 'tavern_4',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [4],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern_5',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },
  {
    id: 'tavern_7',
    name: 'Casa del Mate',
    color: 'yellow',
    age: 1,
    minPlayers: [7],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 5 }],
  },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  {
    id: 'stockade_3',
    name: 'Palenque',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'stockade_7',
    name: 'Palenque',
    color: 'red',
    age: 1,
    minPlayers: [7],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'barracks_3',
    name: 'Toldería de Guerreros',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { ore: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'barracks_5',
    name: 'Toldería de Guerreros',
    color: 'red',
    age: 1,
    minPlayers: [5],
    cost: { ore: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'guard_tower_3',
    name: 'Atalaya',
    color: 'red',
    age: 1,
    minPlayers: [3],
    cost: { clay: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'guard_tower_4',
    name: 'Atalaya',
    color: 'red',
    age: 1,
    minPlayers: [4],
    cost: { clay: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },

  // ── ERA 1 GEMINI BATCH (Completar Red, Green, Yellow, Gray, Blue) ─────────
  // RED
  {
    id: 'puesto_guerreros_3',
    name: 'Puesto de Guerreros',
    color: 'red',
    age: 1,
    minPlayers: [5],
    cost: {},
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'atalaya_madera_3',
    name: 'Atalaya de Madera',
    color: 'red',
    age: 1,
    minPlayers: [4],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'caballeriza_rastrillada',
    name: 'Caballeriza de Rastrillada',
    color: 'red',
    age: 1,
    minPlayers: [4],
    cost: { clay: 1, wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'fortin_empalizada_rio',
    name: 'Fortín de la Ribera',
    color: 'red',
    age: 1,
    minPlayers: [5],
    cost: { stone: 1, wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },

  // GREEN
  {
    id: 'curandero_3',
    name: 'Ruca del Curandero',
    color: 'green',
    age: 1,
    minPlayers: [5],
    cost: { loom: 1 },
    chainTo: ['Observatorio de la Cruz del Sur', 'Práctica de Arquería'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'taller_arqueria_3',
    name: 'Taller de Arquería',
    color: 'green',
    age: 1,
    minPlayers: [4],
    cost: { glass: 1 },
    chainTo: ['Taller de Boleadoras y Lazos', 'Huerto de Hierbas Curativas'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'piedras_pintadas_3',
    name: 'Piedras Pintadas',
    color: 'green',
    age: 1,
    minPlayers: [3],
    cost: { papyrus: 1 },
    chainTo: ['Círculo de Historias Orales'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },

  // YELLOW
  {
    id: 'feria_trueque_3',
    name: 'Feria de Trueque',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 4 }],
  },
  {
    id: 'arriero_monte_3',
    name: 'Arriero del Monte',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins_from_brown', per_brown: 1, include_neighbors: false }],
  },
  {
    id: 'embarcadero_lago_3',
    name: 'Embarcadero del Lago',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: { wood: 1 },
    chainTo: ['Mercado de las Carretas'],
    effects: [{ type: 'trade_discount_both', resources: ['brown', 'gray'] }],
  },
  {
    id: 'pulperia_del_camino',
    name: 'Pulpería del Camino',
    color: 'yellow',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins', amount: 2 }],
  },

  // GRAY
  {
    id: 'taller_pan_pinyon',
    name: 'Horno de Piñón y Trigo',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: { wood: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },
  {
    id: 'corral_acopio_pirca',
    name: 'Corral de Acopio en Pirca',
    color: 'gray',
    age: 1,
    minPlayers: [4],
    cost: { stone: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'tranquera_lenga_reforzada',
    name: 'Tranquera de Lenga',
    color: 'gray',
    age: 1,
    minPlayers: [5],
    cost: { wood: 1, coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'maestria_obsidiana_volcanica',
    name: 'Taller de Obsidiana Maestra',
    color: 'gray',
    age: 1,
    minPlayers: [6],
    cost: { stone: 1, coins: 2 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'witral_gran_telar',
    name: 'Witral del Gran Telar',
    color: 'gray',
    age: 1,
    minPlayers: [3],
    cost: { wood: 1, coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },

  // BLUE
  {
    id: 'altar_piedras_3',
    name: 'Altar de Piedras',
    color: 'blue',
    age: 1,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'victory_points', points: 2 }],
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// ERA II
// ══════════════════════════════════════════════════════════════════════════════
export const AGE2_CARDS: Card[] = [
  // ── MATERIA PRIMA (brown) ─────────────────────────────────────────────────
  {
    id: 'bosque_alerces_milenarios',
    name: 'Bosque de Alerces Milenarios',
    color: 'brown',
    age: 2,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'wood' }, { type: 'produce_resource', resource: 'wood' }],
  },
  {
    id: 'cantera_granito_sur',
    name: 'Cantera de Granito del Sur',
    color: 'brown',
    age: 2,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }, { type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'yacimiento_arcilla_roja',
    name: 'Yacimiento de Arcilla Roja',
    color: 'brown',
    age: 2,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'clay' }, { type: 'produce_resource', resource: 'clay' }],
  },
  {
    id: 'veta_cobre_profunda',
    name: 'Veta de Cobre Profunda',
    color: 'brown',
    age: 2,
    minPlayers: [4],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }],
  },

  // ── MANUFACTURA (gray) ────────────────────────────────────────────────────
  {
    id: 'tejeduria_mantas_finas',
    name: 'Tejeduría de Mantas Finas',
    color: 'gray',
    age: 2,
    minPlayers: [3],
    cost: { coins: 2 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'taller_puntas_obsidiana',
    name: 'Taller de Puntas de Obsidiana',
    color: 'gray',
    age: 2,
    minPlayers: [3],
    cost: { coins: 1, stone: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'curtiembre_cuero_fino',
    name: 'Curtiembre de Cuero Fino',
    color: 'gray',
    age: 2,
    minPlayers: [4],
    cost: { coins: 1, wood: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },
  {
    id: 'artesania_cuero_crudo',
    name: 'Artesanía en Cuero Crudo',
    color: 'gray',
    age: 2,
    minPlayers: [5],
    cost: { coins: 1, clay: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },

  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  {
    id: 'maloca_ceremonial',
    name: 'Maloca Ceremonial',
    color: 'blue',
    age: 2,
    minPlayers: [3],
    cost: { wood: 2, stone: 1 },
    chainTo: ['Asamblea Grande'],
    effects: [{ type: 'victory_points', points: 5 }],
  },
  {
    id: 'parlamento_de_lonkos',
    name: 'Parlamento de Lonkos',
    color: 'blue',
    age: 2,
    minPlayers: [4],
    cost: { clay: 2, wood: 1 },
    chainTo: ['Nguillatún'],
    effects: [{ type: 'victory_points', points: 4 }],
  },
  {
    id: 'menhir_de_los_antiguos',
    name: 'Menhir de los Antiguos',
    color: 'blue',
    age: 2,
    minPlayers: [5],
    cost: { stone: 3 },
    chainTo: [],
    effects: [{ type: 'victory_points', points: 4 }],
  },
  {
    id: 'escuela_de_la_naturaleza',
    name: 'Escuela de la Naturaleza',
    color: 'blue',
    age: 2,
    minPlayers: [3],
    cost: { wood: 1, papyrus: 1 },
    chainTo: ['Jardín del Sur'],
    effects: [{ type: 'victory_points', points: 3 }],
  },
  {
    id: 'sitio_sagrado_copihue',
    name: 'Sitio Sagrado del Copihue',
    color: 'blue',
    age: 2,
    minPlayers: [6],
    cost: { clay: 1, glass: 1 },
    chainTo: [],
    effects: [{ type: 'victory_points', points: 3 }],
  },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  {
    id: 'lanceros_de_la_estepa',
    name: 'Lanceros de la Estepa',
    color: 'red',
    age: 2,
    minPlayers: [3],
    cost: { wood: 1, ore: 2 },
    chainTo: ['Tolderia de Armas'],
    effects: [{ type: 'shields', count: 2 }],
  },
  {
    id: 'pirca_de_fortificacion',
    name: 'Pirca de Fortificación',
    color: 'red',
    age: 2,
    minPlayers: [4],
    cost: { stone: 2 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'puesto_guardia_desierto',
    name: 'Puesto de Guardia del Desierto',
    color: 'red',
    age: 2,
    minPlayers: [5],
    cost: { clay: 1, wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 1 }],
  },
  {
    id: 'mirador_de_los_andes',
    name: 'Mirador de los Andes',
    color: 'red',
    age: 2,
    minPlayers: [3],
    cost: { wood: 2, glass: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 2 }],
  },

  {
    id: 'tropa_boleadoras',
    name: 'Tropa de Boleadoras',
    color: 'red',
    age: 2,
    minPlayers: [3],
    cost: { ore: 1, wood: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 2 }],
  },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  {
    id: 'observatorio_cruz_del_sur',
    name: 'Observatorio de la Cruz del Sur',
    color: 'green',
    age: 2,
    minPlayers: [3],
    cost: { stone: 1, glass: 1 },
    chainTo: ['Círculo de Ancianos', 'Academia del Saber'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'taller_boleadoras_lazos',
    name: 'Taller de Boleadoras y Lazos',
    color: 'green',
    age: 2,
    minPlayers: [3],
    cost: { stone: 1, loom: 1 },
    chainTo: ['Observatorio del Cielo', 'Estudio del Cielo'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },
  {
    id: 'circulo_historias_orales',
    name: 'Círculo de Historias Orales',
    color: 'green',
    age: 2,
    minPlayers: [4],
    cost: { wood: 1, papyrus: 1 },
    chainTo: ['Universidad del Sur'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },
  {
    id: 'practica_de_arqueria',
    name: 'Práctica de Arquería',
    color: 'green',
    age: 2,
    minPlayers: [5],
    cost: { wood: 2 },
    chainTo: ['Academia del Saber'],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
  {
    id: 'huerto_hierbas_curativas',
    name: 'Huerto de Hierbas Curativas',
    color: 'green',
    age: 2,
    minPlayers: [6],
    cost: { clay: 2 },
    chainTo: ['Estudio del Cielo'],
    effects: [{ type: 'science', symbol: 'gear' }],
  },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  {
    id: 'ruta_sal_y_oro',
    name: 'Ruta de la Sal y el Oro',
    color: 'yellow',
    age: 2,
    minPlayers: [3],
    cost: { wood: 1, stone: 1 },
    chainTo: [],
    effects: [{ type: 'coins', amount: 6 }],
  },
  {
    id: 'feria_de_primavera',
    name: 'Feria de Trueque de Primavera',
    color: 'yellow',
    age: 2,
    minPlayers: [4],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'coins', amount: 4 }, { type: 'victory_points', points: 1 }],
  },
  {
    id: 'pulperia_de_frontera',
    name: 'Pulpería de Frontera',
    color: 'yellow',
    age: 2,
    minPlayers: [5],
    cost: { clay: 1 },
    chainTo: [],
    effects: [{ type: 'coins', amount: 3 }],
  },
  {
    id: 'deposito_de_vituallas',
    name: 'Depósito de Vituallas',
    color: 'yellow',
    age: 2,
    minPlayers: [3],
    cost: { wood: 1, clay: 1 },
    chainTo: ['Fogón Guía'],
    effects: [{ type: 'coins_from_yellow', per_yellow: 2 }],
  },
  {
    id: 'mercado_de_las_carretas',
    name: 'Mercado de las Carretas',
    color: 'yellow',
    age: 2,
    minPlayers: [6],
    cost: { stone: 1 },
    chainTo: ['Caleta'],
    effects: [{ type: 'trade_discount_both', resources: ['brown', 'gray'] }],
  },

  // ── CARTAS FALTANTES — añadidas para garantizar 7×N cartas por era ─────────

  // ── MIN 3 (7 tarjetas) ────────────────────────────────────────────────────
  {
    id: 'pedernal_del_sur',
    name: 'Pedernal del Sur',
    color: 'brown',
    age: 2,
    minPlayers: [3],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'tolderia_cuero_crudo',
    name: 'Toldería de Cuero Crudo',
    color: 'gray',
    age: 2,
    minPlayers: [3],
    cost: { coins: 2 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'papyrus' }],
  },
  {
    id: 'escuela_del_machi',
    name: 'Escuela del Machi',
    color: 'green',
    age: 2,
    minPlayers: [3],
    cost: { wood: 1, papyrus: 1 },
    chainTo: ['Universidad del Sur'],
    effects: [{ type: 'science', symbol: 'tablet' }],
  },
  {
    id: 'corrales_del_trueque',
    name: 'Corrales del Trueque',
    color: 'yellow',
    age: 2,
    minPlayers: [3],
    cost: { clay: 1, ore: 1 },
    chainTo: [],
    effects: [{ type: 'trade_discount_left', resources: ['brown', 'gray'] }],
  },
  {
    id: 'paso_de_los_andes',
    name: 'Paso de los Andes',
    color: 'yellow',
    age: 2,
    minPlayers: [3],
    cost: { ore: 1, stone: 1 },
    chainTo: [],
    effects: [{ type: 'trade_discount_right', resources: ['brown', 'gray'] }],
  },
  {
    id: 'nillatun_mayor',
    name: 'Ñillatún Mayor',
    color: 'blue',
    age: 2,
    minPlayers: [3],
    cost: { clay: 2, stone: 1 },
    chainTo: [],
    effects: [{ type: 'victory_points', points: 4 }],
  },
  {
    id: 'vineria_del_viento',
    name: 'Viñería del Viento',
    color: 'yellow',
    age: 2,
    minPlayers: [3],
    cost: {},
    chainTo: [],
    effects: [{ type: 'coins_from_brown', per_brown: 1, include_neighbors: true }],
  },

  // ── MIN 4 (1 tarjeta) ─────────────────────────────────────────────────────
  {
    id: 'caravana_esteparia',
    name: 'Caravana Esteparia',
    color: 'yellow',
    age: 2,
    minPlayers: [4],
    cost: { stone: 1, loom: 1 },
    chainTo: [],
    effects: [{ type: 'trade_discount_both', resources: ['brown'] }],
  },

  // ── MIN 5 (2 tarjetas) ────────────────────────────────────────────────────
  {
    id: 'arsenal_del_alto',
    name: 'Arsenal del Alto',
    color: 'red',
    age: 2,
    minPlayers: [5],
    cost: { ore: 2, stone: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 2 }],
  },
  {
    id: 'palacio_del_viento',
    name: 'Palacio del Viento',
    color: 'blue',
    age: 2,
    minPlayers: [5],
    cost: { clay: 3, glass: 1 },
    chainTo: [],
    effects: [{ type: 'victory_points', points: 5 }],
  },

  // ── MIN 6 (4 tarjetas) ────────────────────────────────────────────────────
  {
    id: 'bodega_del_sur',
    name: 'Bodega del Sur',
    color: 'brown',
    age: 2,
    minPlayers: [6],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'stone' }, { type: 'produce_resource', resource: 'stone' }],
  },
  {
    id: 'hilado_de_vicuna',
    name: 'Hilado de Vicuña',
    color: 'gray',
    age: 2,
    minPlayers: [6],
    cost: { coins: 2 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'loom' }],
  },
  {
    id: 'academia_militar_del_sur',
    name: 'Academia Militar del Sur',
    color: 'red',
    age: 2,
    minPlayers: [6],
    cost: { clay: 2, ore: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 2 }],
  },
  {
    id: 'plaza_de_intercambio',
    name: 'Plaza de Intercambio',
    color: 'yellow',
    age: 2,
    minPlayers: [6],
    cost: { stone: 1 },
    chainTo: [],
    effects: [{ type: 'coins_from_yellow', per_yellow: 1 }],
  },

  // ── MIN 7 (7 tarjetas) ────────────────────────────────────────────────────
  {
    id: 'mina_de_cobre_patagonica',
    name: 'Mina de Cobre Patagónica',
    color: 'brown',
    age: 2,
    minPlayers: [7],
    cost: { coins: 1 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }],
  },
  {
    id: 'fragua_del_condor',
    name: 'Fragua del Cóndor',
    color: 'brown',
    age: 2,
    minPlayers: [7],
    cost: {},
    chainTo: [],
    effects: [{ type: 'produce_choice', options: ['stone', 'ore'] }],
  },
  {
    id: 'telar_ceremonial',
    name: 'Telar Ceremonial',
    color: 'gray',
    age: 2,
    minPlayers: [7],
    cost: { coins: 2 },
    chainTo: [],
    effects: [{ type: 'produce_resource', resource: 'glass' }],
  },
  {
    id: 'salon_del_lonko',
    name: 'Salón del Lonko',
    color: 'blue',
    age: 2,
    minPlayers: [7],
    cost: { stone: 2, glass: 1 },
    chainTo: [],
    effects: [{ type: 'victory_points', points: 4 }],
  },
  {
    id: 'brigada_de_lanzas',
    name: 'Brigada de Lanzas',
    color: 'red',
    age: 2,
    minPlayers: [7],
    cost: { wood: 2, clay: 1 },
    chainTo: [],
    effects: [{ type: 'shields', count: 2 }],
  },
  {
    id: 'corredor_de_intercambio',
    name: 'Corredor de Intercambio',
    color: 'yellow',
    age: 2,
    minPlayers: [7],
    cost: { stone: 1, ore: 1 },
    chainTo: [],
    effects: [{ type: 'trade_discount_both', resources: ['brown', 'gray'] }],
  },
  {
    id: 'centro_de_sabiduria',
    name: 'Centro de Sabiduría',
    color: 'green',
    age: 2,
    minPlayers: [7],
    cost: { ore: 2, loom: 1 },
    chainTo: [],
    effects: [{ type: 'science', symbol: 'compass' }],
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// ERA III
// ══════════════════════════════════════════════════════════════════════════════
export const AGE3_CARDS: Card[] = [
  // ── ESTRUCTURAS CIVILES (blue) ────────────────────────────────────────────
  { id: 'a3_pantheon_3', name: 'Nguillatún', color: 'blue', age: 3, minPlayers: [3], cost: { clay: 1, wood: 1, papyrus: 1, loom: 1, glass: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'a3_pantheon_6', name: 'Nguillatún', color: 'blue', age: 3, minPlayers: [6], cost: { clay: 1, wood: 1, papyrus: 1, loom: 1, glass: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'a3_gardens_3', name: 'Jardín del Sur', color: 'blue', age: 3, minPlayers: [3], cost: { clay: 2, wood: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a3_gardens_4', name: 'Jardín del Sur', color: 'blue', age: 3, minPlayers: [4], cost: { clay: 2, wood: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'a3_town_hall_3', name: 'Asamblea del Pueblo', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 2, wood: 1, glass: 1, ore: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_town_hall_5', name: 'Asamblea del Pueblo', color: 'blue', age: 3, minPlayers: [5], cost: { stone: 2, wood: 1, glass: 1, ore: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_palace_3', name: 'Ruka del Lonko Mayor', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 1, clay: 1, ore: 1, wood: 1, glass: 1, loom: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 8 }] },
  { id: 'a3_palace_7', name: 'Ruka del Lonko Mayor', color: 'blue', age: 3, minPlayers: [7], cost: { stone: 1, clay: 1, ore: 1, wood: 1, glass: 1, loom: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 8 }] },
  { id: 'a3_senate_3', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [3], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_senate_5', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [5], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'a3_senate_7', name: 'Asamblea Grande', color: 'blue', age: 3, minPlayers: [7], cost: { wood: 2, stone: 1, ore: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },

  // ── ESTRUCTURAS CIENTÍFICAS (green) ──────────────────────────────────────
  { id: 'a3_lodge_3', name: 'Círculo de Ancianos', color: 'green', age: 3, minPlayers: [3], cost: { clay: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_lodge_6', name: 'Círculo de Ancianos', color: 'green', age: 3, minPlayers: [6], cost: { clay: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_observatory_3', name: 'Observatorio del Cielo', color: 'green', age: 3, minPlayers: [3], cost: { ore: 2, wood: 1, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_observatory_7', name: 'Observatorio del Cielo', color: 'green', age: 3, minPlayers: [7], cost: { ore: 2, wood: 1, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_university_3', name: 'Universidad del Sur', color: 'green', age: 3, minPlayers: [3], cost: { wood: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a3_university_4', name: 'Universidad del Sur', color: 'green', age: 3, minPlayers: [4], cost: { wood: 2, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'a3_academy_3', name: 'Academia del Saber', color: 'green', age: 3, minPlayers: [3], cost: { stone: 3, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_academy_6', name: 'Academia del Saber', color: 'green', age: 3, minPlayers: [6], cost: { stone: 3, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'a3_study_3', name: 'Estudio del Cielo', color: 'green', age: 3, minPlayers: [3], cost: { wood: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'a3_study_5', name: 'Estudio del Cielo', color: 'green', age: 3, minPlayers: [5], cost: { wood: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },

  // ── ESTRUCTURAS COMERCIALES (yellow) ─────────────────────────────────────
  { id: 'a3_haven_3', name: 'Caleta', color: 'yellow', age: 3, minPlayers: [3], cost: { ore: 1, loom: 1, wood: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_brown', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_haven_4', name: 'Caleta', color: 'yellow', age: 3, minPlayers: [4], cost: { ore: 1, loom: 1, wood: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_brown', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_lighthouse_3', name: 'Fogón Guía', color: 'yellow', age: 3, minPlayers: [3], cost: { stone: 1, glass: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_yellow', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_lighthouse_6', name: 'Fogón Guía', color: 'yellow', age: 3, minPlayers: [6], cost: { stone: 1, glass: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_yellow', per_card: 1, vp_per_card: 1 }] },
  { id: 'a3_chamber_4', name: 'Cámara del Trueque', color: 'yellow', age: 3, minPlayers: [4], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_gray', per_card: 2, vp_per_card: 2 }] },
  { id: 'a3_chamber_6', name: 'Cámara del Trueque', color: 'yellow', age: 3, minPlayers: [6], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_gray', per_card: 2, vp_per_card: 2 }] },
  { id: 'a3_arena_3', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [3], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },
  { id: 'a3_arena_5', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [5], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },
  { id: 'a3_arena_7', name: 'Ring de Lucha', color: 'yellow', age: 3, minPlayers: [7], cost: { stone: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins_and_vp_from_wonder', per_stage: 3, vp_per_stage: 1 }] },

  // ── ESTRUCTURAS MILITARES (red) ───────────────────────────────────────────
  { id: 'a3_fortifications_3', name: 'Fortificación del Malón', color: 'red', age: 3, minPlayers: [3], cost: { ore: 3, stone: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_fortifications_7', name: 'Fortificación del Malón', color: 'red', age: 3, minPlayers: [7], cost: { ore: 3, stone: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_4', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [4], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_5', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [5], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_circus_6', name: 'Ruedo de Guerra', color: 'red', age: 3, minPlayers: [6], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_3', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [3], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_4', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [4], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_arsenal_7', name: 'Tolderia de Armas', color: 'red', age: 3, minPlayers: [7], cost: { wood: 2, ore: 1, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_siege_workshop_3', name: 'Taller de Lanzas', color: 'red', age: 3, minPlayers: [3], cost: { clay: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'a3_siege_workshop_5', name: 'Taller de Lanzas', color: 'red', age: 3, minPlayers: [5], cost: { clay: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },

  // ── GREMIOS (purple) — Era III; deckBuilder selects playerCount+2 randomly ──
  { id: 'g_workers', name: 'Lof de Trabajadores', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, clay: 1, wood: 1, stone: 1 }, chainTo: [], effects: [{ type: 'vp_from_brown_neighbors', per_card: 1 }] },
  { id: 'g_craftsmens', name: 'Lof de Artesanos', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, stone: 2 }, chainTo: [], effects: [{ type: 'vp_from_gray_neighbors', per_card: 2 }] },
  { id: 'g_traders', name: 'Lof de Comerciantes', color: 'purple', age: 3, minPlayers: [3], cost: { glass: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_yellow_neighbors', per_card: 1 }] },
  { id: 'g_philosophers', name: 'Lof de Machis', color: 'purple', age: 3, minPlayers: [3], cost: { clay: 3, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_green_neighbors', per_card: 1 }] },
  { id: 'g_spies', name: 'Lof de Rastreadores', color: 'purple', age: 3, minPlayers: [3], cost: { clay: 3, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_red_neighbors', per_card: 1 }] },
  { id: 'g_magistrates', name: 'Lof de Lonkos', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 3, stone: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_blue_neighbors', per_card: 1 }] },
  { id: 'g_shipowners', name: 'Lof de Canoeros', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 3, glass: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'vp_from_own_brown_gray_purple' }] },
  { id: 'g_strategists', name: 'Lof de Toquis', color: 'purple', age: 3, minPlayers: [3], cost: { ore: 2, stone: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_defeat_tokens_neighbors' }] },
  { id: 'g_scientists', name: 'Lof de Kimche', color: 'purple', age: 3, minPlayers: [4], cost: { wood: 2, ore: 2, glass: 1 }, chainTo: [], effects: [{ type: 'extra_science_symbol' }] },
  { id: 'g_builders', name: 'Lof de Constructores', color: 'purple', age: 3, minPlayers: [3], cost: { stone: 2, clay: 2, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_wonder_stages', include_self: true }] },

  // ── ERA 3 GEMINI BATCH ────────────────────────────────────────────────────
  // BROWN
  { id: 'puerto_limay_3', name: 'Puerto de Carga del Limay', color: 'brown', age: 3, minPlayers: [3], cost: { coins: 2, wood: 2, stone: 1 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'clay', 'stone', 'ore'] }] },
  { id: 'puerto_limay_4', name: 'Puerto de Carga del Limay', color: 'brown', age: 3, minPlayers: [4], cost: { coins: 2, wood: 2, stone: 1 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'clay', 'stone', 'ore'] }] },
  { id: 'veta_cuarzo_volcanico', name: 'Veta de Cuarzo Volcánico', color: 'brown', age: 3, minPlayers: [3], cost: { ore: 2 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'ore' }, { type: 'produce_resource', resource: 'ore' }] },
  { id: 'estancia_ancestral', name: 'Estancia de Cría Ancestral', color: 'brown', age: 3, minPlayers: [3], cost: { clay: 2, wood: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'clay' }, { type: 'produce_resource', resource: 'clay' }] },
  { id: 'deposito_general_insumos', name: 'Depósito General de Insumos', color: 'brown', age: 3, minPlayers: [3], cost: { coins: 3, wood: 1 }, chainTo: [], effects: [{ type: 'produce_choice', options: ['wood', 'stone'] }] },

  // GRAY
  { id: 'forja_hachas_piedra', name: 'Forja de Hachas de Piedra', color: 'gray', age: 3, minPlayers: [3], cost: { ore: 2, glass: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'glass' }] },
  { id: 'telar_patagonico_maestro', name: 'Gran Telar de la Patagonia', color: 'gray', age: 3, minPlayers: [3], cost: { wood: 2, loom: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'loom' }] },
  { id: 'scriptoria_del_consejo', name: 'Scriptoria del Consejo', color: 'gray', age: 3, minPlayers: [3], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'papyrus' }] },
  { id: 'scriptoria_del_consejo_4', name: 'Scriptoria del Consejo', color: 'gray', age: 3, minPlayers: [4], cost: { clay: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'papyrus' }] },
  { id: 'orfebreria_imperial', name: 'Orfebrería Imperial del Sur', color: 'gray', age: 3, minPlayers: [3], cost: { ore: 2, glass: 1 }, chainTo: [], effects: [{ type: 'produce_resource', resource: 'glass' }] },

  // BLUE
  { id: 'catedral_picos_nevados', name: 'Catedral de los Picos Nevados', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 3, glass: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'catedral_picos_nevados_7', name: 'Catedral de los Picos Nevados', color: 'blue', age: 3, minPlayers: [7], cost: { stone: 3, glass: 1, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 7 }] },
  { id: 'mausoleo_lonko_mayor', name: 'Mausoleo del Lonko Mayor', color: 'blue', age: 3, minPlayers: [3], cost: { clay: 3, papyrus: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 6 }] },
  { id: 'tumulo_real_pirca', name: 'Túmulo Real de Pirca', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 4 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'santuario_fuego_eterno', name: 'Santuario del Fuego Eterno', color: 'blue', age: 3, minPlayers: [3], cost: { wood: 3, glass: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 5 }] },
  { id: 'recinto_espiritu_viento', name: 'Recinto del Espíritu del Viento', color: 'blue', age: 3, minPlayers: [3], cost: { stone: 2, loom: 1 }, chainTo: [], effects: [{ type: 'victory_points', points: 4 }] },

  // RED
  { id: 'guardia_honor_desierto', name: 'Guardia de Honor del Desierto', color: 'red', age: 3, minPlayers: [3], cost: { ore: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'guardia_honor_desierto_4', name: 'Guardia de Honor del Desierto', color: 'red', age: 3, minPlayers: [4], cost: { ore: 3, wood: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'caballeria_pesada_estepa', name: 'Caballería Pesada de la Estepa', color: 'red', age: 3, minPlayers: [3], cost: { ore: 1, wood: 2, loom: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'ciudadela_granito', name: 'Ciudadela de Granito', color: 'red', age: 3, minPlayers: [3], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'ciudadela_granito_5', name: 'Ciudadela de Granito', color: 'red', age: 3, minPlayers: [5], cost: { stone: 3, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 3 }] },
  { id: 'cuartel_general_lanceros', name: 'Cuartel General de Lanceros', color: 'red', age: 3, minPlayers: [3], cost: { wood: 2, ore: 1 }, chainTo: [], effects: [{ type: 'shields', count: 2 }] },

  // GREEN
  { id: 'academia_sabios_mapuches', name: 'Academia de Sabios Mapuches', color: 'green', age: 3, minPlayers: [3], cost: { glass: 2, papyrus: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'cuspide_estrellas', name: 'Cúspide de las Estrellas', color: 'green', age: 3, minPlayers: [3], cost: { stone: 2, glass: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'cuspide_estrellas_5', name: 'Cúspide de las Estrellas', color: 'green', age: 3, minPlayers: [5], cost: { stone: 2, glass: 1, papyrus: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },
  { id: 'registro_cueros_pintados', name: 'Registro de Cueros Pintados', color: 'green', age: 3, minPlayers: [3], cost: { papyrus: 2, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'tablet' }] },
  { id: 'circulo_medicina_ancestral', name: 'Círculo de la Medicina Ancestral', color: 'green', age: 3, minPlayers: [3], cost: { clay: 2, glass: 1, loom: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'compass' }] },
  { id: 'centro_estudios_tierra', name: 'Centro de Estudios de la Tierra', color: 'green', age: 3, minPlayers: [3], cost: { wood: 2, papyrus: 1, glass: 1 }, chainTo: [], effects: [{ type: 'science', symbol: 'gear' }] },

  // YELLOW
  { id: 'camino_inca_del_sur', name: 'Gran Camino del Inca del Sur', color: 'yellow', age: 3, minPlayers: [3], cost: { stone: 2, wood: 1 }, chainTo: [], effects: [{ type: 'coins', amount: 6 }] },
  { id: 'fondo_comunitario_lof', name: 'Fondo Comunitario del Lof', color: 'yellow', age: 3, minPlayers: [3], cost: { coins: 2, clay: 1 }, chainTo: [], effects: [{ type: 'coins', amount: 5 }, { type: 'victory_points', points: 2 }] },
  { id: 'hub_comercial_carretas', name: 'Hub Comercial de las Carretas', color: 'yellow', age: 3, minPlayers: [3], cost: { wood: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins', amount: 3 }, { type: 'trade_discount_both', resources: ['brown', 'gray'] }] },
  { id: 'hub_comercial_carretas_5', name: 'Hub Comercial de las Carretas', color: 'yellow', age: 3, minPlayers: [5], cost: { wood: 2, ore: 1 }, chainTo: [], effects: [{ type: 'coins', amount: 3 }, { type: 'trade_discount_both', resources: ['brown', 'gray'] }] },

  // GREMIOS adicionales de Gemini
  { id: 'logia_tejedores', name: 'Logia de los Tejedores', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 1, stone: 1, loom: 2 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'gray', per_card: 1 }] },
  { id: 'hermandad_rastreadores', name: 'Hermandad de los Rastreadores', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 2, ore: 1, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'brown', per_card: 1 }] },
  { id: 'alianza_navegantes', name: 'Alianza de los Navegantes', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 2, stone: 1, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'blue', per_card: 1 }] },
  { id: 'cofradia_defensores', name: 'Cofradía de los Defensores', color: 'purple', age: 3, minPlayers: [3], cost: { stone: 2, ore: 2 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'red', per_card: 1 }] },
  { id: 'logia_astronomos', name: 'Logia de los Astrónomos', color: 'purple', age: 3, minPlayers: [3], cost: { stone: 1, glass: 1, papyrus: 1, loom: 1 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'green', per_card: 1 }] },
  { id: 'union_pulperos', name: 'Unión de Pulperos', color: 'purple', age: 3, minPlayers: [3], cost: { wood: 1, clay: 1, papyrus: 2 }, chainTo: [], effects: [{ type: 'vp_from_own_color', color: 'yellow', per_card: 1 }] },
  { id: 'hermandad_canteros', name: 'Hermandad de los Canteros', color: 'purple', age: 3, minPlayers: [3], cost: { stone: 3, glass: 1 }, chainTo: [], effects: [{ type: 'vp_from_wonder_stages', include_self: true }] },
];
